# Generated by Django 3.1.7 on 2021-05-18 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tapasapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=300)),
                ('password', models.CharField(max_length=300)),
            ],
        ),
    ]
